spring:
  application:
    name: drools-rule
  datasource:
    url: jdbc:mysql://localhost:3305/my_stu
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

server:
  port: 8080
