package rules
dialect "java"

import com.zero.framework.droolsrule.model.People
import  java.lang.Integer

global com.zero.framework.droolsrule.service.GlobalService service
global java.util.List list
global com.zero.framework.droolsrule.model.NumCount numCount

rule "global"

    when
        People(drlType == "global")
        $p : People() from service.getPeoples()
    then
        list.add($p);
        numCount.plus();
end