package rules
import com.zero.framework.droolsrule.model.People
dialect  "java"

rule "man"
    when
        $p : People(sex == 1 && drlType == "people")
    then
        $p.setSexString("男生");
        update($p);
        System.out.println($p.getName() + "是男孩");
end

rule "girl"
    when
        $p : People(sex == 0 && drlType == "people")
    then
        $p.setSexString("女生");
        update($p);
        System.out.println($p.getName() + "是女孩");
end



rule 'update1'
    when
       $p : People(drlType == "update" && sex == 0)
    then
        System.out.println("update1执行====" + $p);
        $p.setSex(1);
        update($p)
end

rule 'update2'
    when
       $p : People(drlType == "update" && sex == 1)
    then
        System.out.println("update2执行====" + $p);
    end
rule 'modify'
    when
      $p : People(drlType == "update" && sex == 1)
    then
       System.out.println("update3执行====" + $p);
       modify($p){
         setSex(-1)
       }
end
